---
driver:
 name: docker

provisioner:
 name: chef_zero

platforms:
 - name: centos-6.5
   driver_config:
    forward:
      - 27018:27018

suites:
  - name: default
    run_list:
      - recipe[elephant-mongodb::default]
    attributes:
