name 'elephant-mongodb'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures elephant-mongodb'
long_description 'Installs/Configures elephant-mongodb'
version '0.1.0'
